// ---------------------------------------------------------------- //
// This file is autogenerated by pioasm version 2.2.0; do not edit! //
// ---------------------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// ----------------------- //
// spi_cpha0_cs_active_low //
// ----------------------- //

#define spi_cpha0_cs_active_low_wrap_target 0
#define spi_cpha0_cs_active_low_wrap 13
#define spi_cpha0_cs_active_low_pio_version 1

static const uint16_t spi_cpha0_cs_active_low_program_instructions[] = {
            //     .wrap_target
    0x2011, //  0: wait   0 gpio, 17
    0xe027, //  1: set    x, 7
    0x2092, //  2: wait   1 gpio, 18
    0x4001, //  3: in     pins, 1
    0x2012, //  4: wait   0 gpio, 18
    0x6001, //  5: out    pins, 1
    0x00cc, //  6: jmp    pin, 12
    0x0042, //  7: jmp    x--, 2
    0x8000, //  8: push   noblock
    0x8080, //  9: pull   noblock
    0xa0e7, // 10: mov    osr, osr
    0x0001, // 11: jmp    1
    0xa0e3, // 12: mov    osr, null
    0x6060, // 13: out    null, 32
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program spi_cpha0_cs_active_low_program = {
    .instructions = spi_cpha0_cs_active_low_program_instructions,
    .length = 14,
    .origin = -1,
    .pio_version = spi_cpha0_cs_active_low_pio_version,
#if PICO_PIO_VERSION > 0
    .used_gpio_ranges = 0x2
#endif
};

static inline pio_sm_config spi_cpha0_cs_active_low_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + spi_cpha0_cs_active_low_wrap_target, offset + spi_cpha0_cs_active_low_wrap);
    return c;
}
#endif

