// ---------------------------------------------------------------- //
// This file is autogenerated by pioasm version 2.2.0; do not edit! //
// ---------------------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// --------- //
// telemetry //
// --------- //

#define telemetry_wrap_target 0
#define telemetry_wrap 5
#define telemetry_pio_version 1

static const uint16_t telemetry_program_instructions[] = {
            //     .wrap_target
    0x2020, //  0: wait   0 pin, 0
    0xea27, //  1: set    x, 7                   [10]
    0xea27, //  2: set    x, 7                   [10]
    0x4001, //  3: in     pins, 1
    0x0643, //  4: jmp    x--, 3                 [6]
    0x8020, //  5: push   block
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program telemetry_program = {
    .instructions = telemetry_program_instructions,
    .length = 6,
    .origin = -1,
    .pio_version = telemetry_pio_version,
#if PICO_PIO_VERSION > 0
    .used_gpio_ranges = 0x0
#endif
};

static inline pio_sm_config telemetry_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + telemetry_wrap_target, offset + telemetry_wrap);
    return c;
}

#include "hardware/clocks.h"
#include "hardware/gpio.h"
static inline void telemetry_program_init(PIO pio, uint sm, uint offset, uint pin) {
    pio_sm_config c = telemetry_program_get_default_config(offset);
    // Set the IN base pin to the provided pin
    sm_config_set_in_pins(&c, pin);
    // Set this pin's GPIO function (connect PIO to the pad)
    pio_gpio_init(pio, pin);
    // Set pin direction to input
    pio_sm_set_consecutive_pindirs(pio, sm, pin, 1, false);
    // Shift right (LSB first for UART), autopush=false (we push manually), threshold=32 (ignored)
    sm_config_set_in_shift(&c, true, false, 32);
    sm_config_set_fifo_join(&c, PIO_FIFO_JOIN_RX);
    // Clock divider
    // We want 8 cycles per bit.
    // 115200 baud.
    float div = (float)clock_get_hz(clk_sys) / (115200 * 8);
    sm_config_set_clkdiv(&c, div);
    pio_sm_init(pio, sm, offset, &c);
    pio_sm_set_enabled(pio, sm, true);
}

#endif

