// ---------------------------------------------------------------- //
// This file is autogenerated by pioasm version 2.2.0; do not edit! //
// ---------------------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// ----- //
// dshot //
// ----- //

#define dshot_wrap_target 0
#define dshot_wrap 8
#define dshot_pio_version 1

static const uint16_t dshot_program_instructions[] = {
            //     .wrap_target
    0x80a0, //  0: pull   block           side 0
    0xe02f, //  1: set    x, 15           side 0
    0x7041, //  2: out    y, 1            side 1
    0x1066, //  3: jmp    !y, 6           side 1
    0xb342, //  4: nop                    side 1 [3]
    0x0102, //  5: jmp    2               side 0 [1]
    0xb042, //  6: nop                    side 1
    0xa242, //  7: nop                    side 0 [2]
    0x0102, //  8: jmp    2               side 0 [1]
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program dshot_program = {
    .instructions = dshot_program_instructions,
    .length = 9,
    .origin = -1,
    .pio_version = dshot_pio_version,
#if PICO_PIO_VERSION > 0
    .used_gpio_ranges = 0x0
#endif
};

static inline pio_sm_config dshot_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + dshot_wrap_target, offset + dshot_wrap);
    sm_config_set_sideset(&c, 1, false, false);
    return c;
}

#include "hardware/clocks.h"
#include "hardware/gpio.h"
static inline void dshot_program_init(PIO pio, uint sm, uint offset, uint pin) {
    pio_sm_config c = dshot_program_get_default_config(offset);
    sm_config_set_sideset_pins(&c, pin);
    pio_sm_set_consecutive_pindirs(pio, sm, pin, 1, true);
    pio_gpio_init(pio, pin);
    // DShot is MSB first. 
    // shift_right=false (shift left), autopull=false
    // We write data left-aligned or rely on pull behavior.
    // If we shift left, 'out' takes from the MSB (bit 31).
    sm_config_set_out_shift(&c, false, false, 32); 
    sm_config_set_fifo_join(&c, PIO_FIFO_JOIN_TX);
    pio_sm_init(pio, sm, offset, &c);
}

#endif

